### ISSUE TITLE
Add To GitHub Pages

### ISSUE THREAD

**Issue by josh-everett01** [josh-everett01/vue_travel_tracker#5]
Deploy projects through GitHub Pages. 

### Checks:
- [ ] travel_tracker repository is deployed on github pages, tracking the master branch
- [ ] project can be viewed online - (paste link here)

**Comment by Mycobee** [comment]
Lets change "Heroku" to "Github Pages" and avoid the TravisCI stuff for heroku at the moment.  We can use that for the next big one

**Comment by Mycobee** [comment]
@josh-everett01 this issue, the travis CI stuff, the Readme, and the linter should be implemented in the very beginning of the project.  The linter isn't very useful if it isn't checking your PRs

**Comment by Mycobee** [comment]
also the way travisCI works it should automatically push your code to github pages so you don't have to do that manually
